name=input ("what is your name?") 
print ("wao", name , "what a nice name !")
age =input ("whats your age?")
print ("wohhoo", "thats great", "perfect age", age , "year" ,"to experience this scheme of ours ")
color= input ("what's your favourite color ?")
print("thats great we have your favourite colour themed too!")
city=input ("what is your location?")
print ("we ship to", city)
print("for confirmation please press ok !")
